# Generated by Django 4.2.7 on 2025-03-31 12:53

import academy.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (узбекский)"
                    ),
                ),
                (
                    "short_description_uz",
                    models.CharField(
                        max_length=300, verbose_name="Краткое описание (узбекский)"
                    ),
                ),
                ("content_uz", models.TextField(verbose_name="Содержание (узбекский)")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (русский)"
                    ),
                ),
                (
                    "short_description_ru",
                    models.CharField(
                        max_length=300, verbose_name="Краткое описание (русский)"
                    ),
                ),
                ("content_ru", models.TextField(verbose_name="Содержание (русский)")),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=academy.models.news_image_upload_to,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "ordering": ["-published_date"],
            },
        ),
    ]
